### ISSUE TITLE
new fork?

### ISSUE THREAD

**Issue by urfausto** [Bob-Roberts/Leoh#1]
it would be awesome but is it possible to upload a fresh version of this if somebody took care of the coding process?

i use this extension because it is the most advanced one even though being a bit old and not updated. i think it could be faster and lighter since chrome's internal code changed a lot in the while...

**Comment by 9021007** [comment]
You could personally take the project in any direction you like, since this is the source code.

**Comment by urfausto** [comment]
> You could personally take the project in any direction you like, since this is the source code.

nice thanks. i'm not personally a coder but i can take this to someone else perhaps!

**Comment by ImprovedTube** [comment]
@Bobrobot1  yet you just archived it but  not write it, so that you didn't add a license?
